# Generated by Django 3.1.6 on 2021-02-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_datatabledefinition_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatabledefinition',
            name='name',
            field=models.CharField(default='updateme', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='datatabledefinition',
            unique_together={('project', 'name')},
        ),
    ]
